### ISSUE TITLE
自己又继承了一层，有好多毛病

### ISSUE THREAD

**Issue by imTango** [newyjp/JPNavigationController#16]
首先是导航栏的背景色不能在继承的navigation的initialize方法调用了 必须在Viewcontroller的viewDidLoad调用，基类重写的了push方法，拦截改变 返回按钮文字都不奏效了，而且还影响了我隐藏tabbar的操作，tabbar一直都在底部，难道非得每次调用push方法然后在hidebottom吗，不闲麻烦吗

**Comment by newyjp** [comment]
结构特殊, 如果你能理解图层逻辑结构就可以知道应该继承哪一个类, 否则, 你可以当做不能继承. 谢谢支持.

**Comment by 008v** [comment]
> 结构特殊, 如果你能理解图层逻辑结构就可以知道应该继承哪一个类, 否则, 你可以当做不能继承. 谢谢支持.

应该继承哪一个类呢？我直接继承于JPNavigationController，然后用init 和 setViewControllers ，再接着左滑push，然后就崩了，告诉我那个自定义的子类没有某些方法
