### ISSUE TITLE
左滑Push的时候直接pop 回来

### ISSUE THREAD

**Issue by Onion520** [newyjp/JPNavigationController#17]
再用的时候发现有左滑动push 到下一个页面的时候 又自己pop回来了  不知道 @newyjp 有没有遇到这种情况

**Comment by Onion520** [comment]
sorry  我的问题    已解决 是因为和FDFullscreenPopGesture   手势冲突了

**Comment by Onion520** [comment]
发现 还是有此问题

**Comment by newyjp** [comment]
检查一下新 push 到的控制器的 -viewDidAppear:  方法里写了什么.

**Comment by Onion520** [comment]
昨晚 看了一下 在
JPNavigationController.m 第164行
// use system pop action.
[self addSystemPopAction:gestureRecognizer];

加一句判断暂时可以解决此问题
CGPoint translationTemp = [gestureRecognizer translationInView:gestureRecognizer.view];
DLog(@"--------------------------------x %f",translation.x);
 if (translationTemp.x != 0) {
    [self addSystemPopAction:gestureRecognizer];
}
@newyjp 看看这里是不是要加一个上下滑动不加pop的判断

**Comment by newyjp** [comment]
这里只是让手势采用系统默认的方式来执行, 并没有做其他的, 你看一下我的 demo 里, 并没有出现你说的问题.

**Comment by qq245124008** [comment]
demo在真机上也出现了这个问题,有时滑动push就直接pop回来了.然后就一直push不上去
