### ISSUE TITLE
跳转崩溃

### ISSUE THREAD

**Issue by DeveInfo** [newyjp/JPNavigationController#20]
appdelegate.m: 
UITabBarController*tab = (UITabBarController*)self.window.rootViewController;
    
    UINavigationController*nvc = tab.selectedViewController;
    
    UIViewController*vc = nvc.visibleViewController;
    
    LessonModel *model = [self getModelDic:userInfo];
    LessonDetailViewController *LDVC = [LessonDetailViewController new];
    LDVC.hidesBottomBarWhenPushed = YES;
    LDVC.model = model;
    [(BaseNavGationController *)vc.navigationController pushViewController:LDVC animated:YES];
崩溃至JPNavigationController.m 147行

**Comment by newyjp** [comment]
请提供更多堆栈信息.
